name: Authentication Service Workflow

on:
  push:
    branches: [ main ]
    paths:
      - CarService/**
  pull_request:
    branches: [ main ]
    paths:
      - CarService/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # checkout the code
      - name: checkout the code
        uses: actions/checkout@v2
